[tool.poetry]
name = "pySimX"
version = "0.1.1"
description = ""
authors = ["jan <jan.gobeli@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sortedcontainers = "^2.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
